# This is a config for E2B sandbox template.
# You can use template ID (81v0za1us7jwczj6ntbv) or template name (v0-nextjs-build-new-v2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("v0-nextjs-build-new-v2") # Sync sandbox
# sandbox = await AsyncSandbox.create("v0-nextjs-build-new-v2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('v0-nextjs-build-new-v2')

team_id = "b1d7d586-9dd0-481c-bcc3-5f7981c6c262"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "v0-nextjs-build-new-v2"
template_id = "81v0za1us7jwczj6ntbv"
